# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbc90fd211d6c3330cbfdbdba193c71158420259f55fc2163ad27c83005a8433d8a42fd20083bf573e1c8d5f3f109e6501b520891b4170cbcc7d8eeb09ac35df

test:
  secret_key_base: 180c260c1fb4254e2d5032c1c67cc018db73b52cb35fb478f72f71320b019c1a9082d40de21d30b21664709b9fde18c5ff99218f7097ab106101b378612ca036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
